In [187]:
import pandas as pd
import unicodedata
from datetime import datetime

In [188]:
df_customers = pd.read_csv("data/olist_customers_dataset.csv")

In [189]:
df_geo = pd.read_csv("data/olist_geolocation_dataset.csv")

In [190]:
df_order_items = pd.read_csv("data/olist_order_items_dataset.csv")

In [191]:
df_order_payments = pd.read_csv("data/olist_order_payments_dataset.csv")

In [192]:
df_order_reviews = pd.read_csv("data/olist_order_reviews_dataset.csv")

In [193]:
df_orders = pd.read_csv("data/olist_orders_dataset.csv")

In [194]:
df_products = pd.read_csv("data/olist_products_dataset.csv")

In [195]:
df_sellers = pd.read_csv("data/olist_sellers_dataset.csv")

In [196]:
df_product_category_name_translation = pd.read_csv("data/product_category_name_translation.csv")

In [197]:
df_customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [198]:
df_geo

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [199]:
df_products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [200]:
df_customers['customer_zip_code_prefix'] = df_customers['customer_zip_code_prefix'].astype(str)

df_customers['customer_zip_code_prefix'] = df_customers['customer_zip_code_prefix'].str.zfill(5)

In [201]:
condition = df_customers['customer_zip_code_prefix'].str.contains(f'^0\\d+', na=False, regex=True)

df_customers.loc[condition, 'customer_zip_code_prefix'].value_counts()

customer_zip_code_prefix
07600    75
09371    56
06900    46
06454    45
06730    44
         ..
01205     1
03871     1
04319     1
03727     1
05538     1
Name: count, Length: 3869, dtype: int64

In [202]:
df_geo['geolocation_zip_code_prefix'] = df_geo['geolocation_zip_code_prefix'].astype(str)

df_geo['geolocation_zip_code_prefix'] = df_geo['geolocation_zip_code_prefix'].str.zfill(5)

In [203]:
condition = df_geo['geolocation_zip_code_prefix'].str.contains(f'^[1-9]\\d*', na=False, regex=True)

df_geo.loc[condition, 'geolocation_zip_code_prefix'].value_counts()

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
         ...
97843       1
97960       1
98320       1
98825       1
99839       1
Name: count, Length: 14661, dtype: int64

In [204]:
condition = df_geo['geolocation_zip_code_prefix'].str.contains(f'^0\\d*', na=False, regex=True)

df_geo.loc[condition, 'geolocation_zip_code_prefix'].value_counts()

geolocation_zip_code_prefix
07600    587
06454    532
06900    447
06543    436
06730    431
        ...
09602      1
09611      1
09696      1
09869      1
09838      1
Name: count, Length: 4354, dtype: int64

In [205]:
def clean_unicode(text):
    if not isinstance(text, str):
        return text
    
    text = text.lower().strip()
    
    cleaned_text = ''.join(c for c in unicodedata.normalize('NFD', text) if unicodedata.category(c) != 'Mn')
    
    return cleaned_text

Start Cleaning Geolocation City in geo dataset

In [206]:
df_geo['geolocation_city'] = df_geo['geolocation_city'].str.lower()

df_geo['geolocation_city'] = df_geo['geolocation_city'].str.strip()

In [207]:
df_geo['geolocation_city'] = df_geo['geolocation_city'].apply(clean_unicode)

In [208]:
df_geo[df_geo['geolocation_city'].str.contains("paulo")]['geolocation_city'].value_counts()

geolocation_city
sao paulo                      160718
paulo afonso                      434
engenheiro paulo de frontin        81
paulo de faria                     56
paulo frontin                      45
monsenhor paulo                    25
sao paulo das missoes              25
paulo lopes                        22
sao paulo do potengi               18
frei paulo                         11
paulo bento                         8
paulo jacinto                       7
paulo ramos                         7
morro de sao paulo                  3
saopaulo                            2
sao paulo de olivenca               2
sa£o paulo                          1
Name: count, dtype: int64

In [209]:
df_geo[df_geo['geolocation_city'] == 'são paulo']['geolocation_zip_code_prefix']

Series([], Name: geolocation_zip_code_prefix, dtype: str)

In [210]:
sao_paulo_dirty = ['sao paulo', 'são paulo', 'sãopaulo', 'sa£o paulo', 'saopaulo']

df_geo['geolocation_city'] = df_geo['geolocation_city'].replace(sao_paulo_dirty, 'sao paulo')

In [211]:
dominant_city = df_geo.groupby('geolocation_zip_code_prefix')['geolocation_city'].agg(lambda x: x.value_counts().index[0])

In [212]:
dominant_city

geolocation_zip_code_prefix
01001          sao paulo
01002          sao paulo
01003          sao paulo
01004          sao paulo
01005          sao paulo
              ...
99960            charrua
99965         agua santa
99970            ciriaco
99980    david canabarro
99990          muliterno
Name: geolocation_city, Length: 19015, dtype: str

In [213]:
df_geo['geolocation_city'] = df_geo['geolocation_zip_code_prefix'].map(dominant_city)

Start Cleaning customer city in customers dataset

1. pakai replace series by list
2. pakai unicode
3. pakai dominant city by zip code

In [214]:
df_customers[df_customers['customer_city'].str.contains('paulo')]['customer_city'].value_counts()

customer_city
sao paulo                      15540
paulo afonso                      40
engenheiro paulo de frontin        6
paulo frontin                      5
paulo de faria                     5
paulo lopes                        2
paulo jacinto                      2
sao paulo do potengi               2
sao paulo das missoes              2
morro de sao paulo                 1
monsenhor paulo                    1
Name: count, dtype: int64

Products dataset cleaning

In [215]:
df_products['product_category_name'].isna().sum()

np.int64(610)

In [216]:
columns_rename = {
    'product_name_lenght': 'product_name_length',
    'product_description_lenght': 'product_description_length',
    'product_height_cm': 'product_heigth_cm'
}

df_products = df_products.rename(columns=columns_rename)

In [217]:
df_products.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_heigth_cm', 'product_width_cm'],
      dtype='str')

In [218]:
df_products.dtypes

product_id                        str
product_category_name             str
product_name_length           float64
product_description_length    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_heigth_cm             float64
product_width_cm              float64
dtype: object

In [219]:
columns = ['product_name_length', 'product_description_length', 'product_photos_qty']

for col in columns:
    df_products[col] = df_products[col].astype('Int64')

In [220]:
df_products.dtypes

product_id                        str
product_category_name             str
product_name_length             Int64
product_description_length      Int64
product_photos_qty              Int64
product_weight_g              float64
product_length_cm             float64
product_heigth_cm             float64
product_width_cm              float64
dtype: object

In [221]:
df_products[df_products['product_weight_g'] == 0]

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,51,529,1,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,48,528,1,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,53,528,1,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,53,528,1,0.0,30.0,25.0,30.0

In [222]:
df_products[df_products['product_weight_g'].isna()]

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60,865,3,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN

In [223]:
df_products["valid_product_weight_g"] = (df_products['product_weight_g'].notna()) & (df_products['product_weight_g'] > 0)

In [224]:
df_products

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm,valid_product_weight_g
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225.0,16.0,10.0,14.0,True
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000.0,30.0,18.0,20.0,True
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154.0,18.0,9.0,15.0,True
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371.0,26.0,4.0,26.0,True
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625.0,20.0,17.0,13.0,True
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45,67,2,12300.0,40.0,40.0,40.0,True
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41,971,1,1700.0,16.0,19.0,16.0,True
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50,799,1,1400.0,27.0,7.0,27.0,True
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60,156,2,700.0,31.0,13.0,20.0,True
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58,309,1,2083.0,12.0,2.0,7.0,True

In [225]:
length_mean = df_products.groupby('product_category_name')['product_length_cm'].transform('mean')
height_mean = df_products.groupby('product_category_name')['product_heigth_cm'].transform('mean')
width_mean = df_products.groupby('product_category_name')['product_width_cm'].transform('mean')

df_products['product_length_cm'] = df_products['product_length_cm'].fillna(length_mean)
df_products['product_heigth_cm'] = df_products['product_heigth_cm'].fillna(height_mean)
df_products['product_width_cm'] = df_products['product_width_cm'].fillna(width_mean)

In [226]:
df_products[df_products['product_id'] == '09ff539a621711667c43eba6a3bd8466']

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm,valid_product_weight_g
8578,09ff539a621711667c43eba6a3bd8466,bebes,60,865,3,NaN,37.147059,21.617647,28.717865,False

In [227]:
length_mean = df_products['product_length_cm'].mean()
height_mean = df_products['product_heigth_cm'].mean()
width_mean = df_products['product_width_cm'].mean()

df_products['product_length_cm'] = df_products['product_length_cm'].fillna(length_mean)
df_products['product_heigth_cm'] = df_products['product_heigth_cm'].fillna(height_mean)
df_products['product_width_cm'] = df_products['product_width_cm'].fillna(width_mean)

In [228]:
unknown_category_ids = df_products[df_products['product_category_name'].isna()]['product_id']
    
df_products.loc[df_products['product_id'].isin(unknown_category_ids), 'product_category_name'] = "unknown category"

In [229]:
df_products['product_category_name'].isna().sum()

np.int64(0)

In [230]:
df_products[df_products['product_id'] == '09ff539a621711667c43eba6a3bd8466'][
    ['product_category_name', 'product_weight_g', 
     'product_length_cm', 'product_heigth_cm', 'product_width_cm']
]

,product_category_name,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm
8578,bebes,NaN,37.147059,21.617647,28.717865

In [231]:
print(df_orders.dtypes)

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [232]:
print(df_orders.isna().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [233]:
print(df_order_items.dtypes)

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [234]:
print(df_order_items.isna().sum())

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [235]:
df_orders.head(20)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00
11,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08 00:00:00
12,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18 00:00:00
13,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08 00:00:00
14,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21 00:00:00
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04 00:00:00
16,403b97836b0c04a622354cf531062e5f,738b086814c6fcc74b8cc583f8516ee3,delivered,2018-01-02 19:00:43,2018-01-02 19:09:04,2018-01-03 18:19:09,2018-01-20 01:38:59,2018-02-06 00:00:00
17,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,delivered,2017-12-26 23:41:31,2017-12-26 23:50:22,2017-12-28 18:33:05,2018-01-08 22:36:36,2018-01-29 00:00:00
18,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11 00:00:00
19,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23 00:00:00

Save to staged folder

In [238]:
dataFrames = {
    "customers": df_customers,
    "geolocation": df_geo,
    "order_items": df_order_items,
    "orders": df_orders,
    "products": df_products,
    "product_category_name_translation": df_product_category_name_translation
}

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

for name, df in dataFrames.items():    
    file_path = f"staged/{name}_{timestamp}.csv"
    
    df.to_csv(file_path, index=False)
    
    print(f"{file_path} berhasil disimpan")

staged/customers_20260628_225111.csv berhasil disimpan
staged/geolocation_20260628_225111.csv berhasil disimpan
staged/order_items_20260628_225111.csv berhasil disimpan
staged/orders_20260628_225111.csv berhasil disimpan
staged/products_20260628_225111.csv berhasil disimpan
staged/product_category_name_translation_20260628_225111.csv berhasil disimpan