In [1]:
import pandas as pd
import os

In [2]:
data_folder = "data/"
files = [f for f in os.listdir(data_folder) if f.endswith(".csv") ]

In [3]:
for filename in sorted(files):
    df = pd.read_csv(os.path.join(data_folder, filename))
    columns = df.columns

    print(f"Filename: {filename}")

    print("\n=== SHAPE ===")
    print(df.shape)

    print("\n=== DTYPES ===")
    print(df.dtypes)
    
    print("\n=== COLUMNS ===")
    print(columns)
    
    print("\nColumn and Its Type")
    
    cols_and_types = ""
    
    for col in columns:
        col_and_type = f"{col} ({df[col].dtype})"
        if df.columns.get_loc(col) != df.shape[1] - 1:
            col_and_type += ", "
        else: 
            col_and_type += "."
            
        cols_and_types += col_and_type
    
    print(cols_and_types)
    
    print("\n=== 10 First Data ===")
    print(df.head(10))

    print("\n=== NULL COUNT ===")
    print(df.isna().sum())

    print("\n=== DUPLICATE COUNT ===")
    print(df.duplicated().sum())
    
    print("\n==========================\n")

Filename: olist_customers_dataset.csv

=== SHAPE ===
(99441, 5)

=== DTYPES ===
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

=== COLUMNS ===
Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

Column and Its Type
customer_id (str), customer_unique_id (str), customer_zip_code_prefix (int64), customer_city (str), customer_state (str).

=== 10 First Data ===
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
5  879864dab9bc3047522c92c82e1212b8  4c93744516667ad3b8f1fb645a3116a4
6  fd826e7cf63160e536e0908c76c3f441  addec96d2e059c80c30fe6871d30d177
7  5e274e7a0c3809e14aba7ad5aae0d407  57b2a98a409812fe9618067b6b8ebe4f
8  5adf08e34b2e993982a47070956c5c65  1175e95fb47ddff9de6b2b06188f7e0d
9  4b7139f34592b3a31687243a302fa75b  9afe194fb833f79e300e37e580171f22

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP
5                     89254         jaragua do sul             SC
6                      4534              sao paulo             SP
7                     35182                timoteo             MG
8                     81560               curitiba             PR
9                     30575         belo horizonte             MG

=== NULL COUNT ===
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

=== DUPLICATE COUNT ===
0

==========================

Filename: olist_geolocation_dataset.csv

=== SHAPE ===
(1000163, 5)

=== DTYPES ===
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

=== COLUMNS ===
Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='str')

Column and Its Type
geolocation_zip_code_prefix (int64), geolocation_lat (float64), geolocation_lng (float64), geolocation_city (str), geolocation_state (str).

=== 10 First Data ===
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607
5                         1012       -23.547762       -46.635361
6                         1047       -23.546273       -46.641225
7                         1013       -23.546923       -46.634264
8                         1029       -23.543769       -46.634278
9                         1011       -23.547640       -46.636032

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP
5        são paulo                SP
6        sao paulo                SP
7        sao paulo                SP
8        sao paulo                SP
9        sao paulo                SP

=== NULL COUNT ===
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

=== DUPLICATE COUNT ===
261831

==========================

Filename: olist_order_items_dataset.csv

=== SHAPE ===
(112650, 7)

=== DTYPES ===
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

=== COLUMNS ===
Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

Column and Its Type
order_id (str), order_item_id (int64), product_id (str), seller_id (str), shipping_limit_date (str), price (float64), freight_value (float64).

=== 10 First Data ===
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1
5  00048cc3ae777c65dbb7d2a0634bc1ea              1
6  00054e8431b9d7675808bcb819fb4a32              1
7  000576fe39319847cbb9d288c5617fa6              1
8  0005a1a1728c9d785b8e2b08b904576c              1
9  0005f50442cb953dcd1d21e1fb923495              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87
5  ef92defde845ab8450f9d70c526ef70f  6426d21aca402a131fc0a5d0960a3c90
6  8d4f2bb7e93e6710a28f34fa83ee7d28  7040e82f899a04d1b434b795a43b4617
7  557d850972a7d6f792fd18ae1400d9b6  5996cddab893a4652a15592fb58ab8db
8  310ae3c140ff94b03219ad0adc3c778f  a416b6a846a11724393025641d4edd5e
9  4535b0e1091c278dfd193e5a1d63b39f  ba143b05f0110f0dc71ad71b4466ce92

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14
5  2017-05-23 03:55:27   21.90          12.69
6  2017-12-14 12:10:31   19.90          11.85
7  2018-07-10 12:30:45  810.00          70.75
8  2018-03-26 18:31:29  145.95          11.65
9  2018-07-06 14:10:56   53.99          11.40

=== NULL COUNT ===
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

=== DUPLICATE COUNT ===
0

==========================

Filename: olist_order_payments_dataset.csv

=== SHAPE ===
(103886, 5)

=== DTYPES ===
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

=== COLUMNS ===
Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

Column and Its Type
order_id (str), payment_sequential (int64), payment_type (str), payment_installments (int64), payment_value (float64).

=== 10 First Data ===
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card
5  298fcdf1f73eb413e4d26d01b25bc1cd                   1  credit_card
6  771ee386b001f06208a7419e4fc1bbd7                   1  credit_card
7  3d7239c394a212faae122962df514ac7                   1  credit_card
8  1f78449c87a54faf9e96e88ba1491fa9                   1  credit_card
9  0573b5e23cbd798006520e1d5b4c6714                   1       boleto

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45
5                     2          96.12
6                     1          81.16
7                     3          51.84
8                     6         341.09
9                     1          51.95

=== NULL COUNT ===
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

=== DUPLICATE COUNT ===
0

==========================

Filename: olist_order_reviews_dataset.csv

=== SHAPE ===
(99224, 7)

=== DTYPES ===
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

=== COLUMNS ===
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

Column and Its Type
review_id (str), order_id (str), review_score (int64), review_comment_title (str), review_comment_message (str), review_creation_date (str), review_answer_timestamp (str).

=== 10 First Data ===
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1
5  15197aa66ff4d0650b5434f1b46cda19  b18dcdf73be66366873cd26c5724d1dc
6  07f9bee5d1b850860defd761afa7ff16  e48aa0d2dcec3a2e87348811bcfdf22b
7  7c6400515c67679fbee952a7525281ef  c31a859e34e3adac22f376954e19b39d
8  a3f6f7f6f433de0aefbb97da197c554c  9c214ac970e84273583ab523dfafd09b
9  8670d52e15e00043ae7de4c01cc2fe06  b9bf720beb4ab3728760088589c62129

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN
5             1                  NaN
6             5                  NaN
7             5                  NaN
8             5                  NaN
9             4            recomendo

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00
5                                                NaN  2018-04-13 00:00:00
6                                                NaN  2017-07-16 00:00:00
7                                                NaN  2018-08-14 00:00:00
8                                                NaN  2017-05-17 00:00:00
9  aparelho eficiente. no site a marca do aparelh...  2018-05-22 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53
5     2018-04-16 00:39:37
6     2017-07-18 19:30:34
7     2018-08-14 21:36:06
8     2017-05-18 12:05:37
9     2018-05-23 16:45:47

=== NULL COUNT ===
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

=== DUPLICATE COUNT ===
0

==========================

Filename: olist_orders_dataset.csv

=== SHAPE ===
(99441, 8)

=== DTYPES ===
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

=== COLUMNS ===
Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

Column and Its Type
order_id (str), customer_id (str), order_status (str), order_purchase_timestamp (str), order_approved_at (str), order_delivered_carrier_date (str), order_delivered_customer_date (str), order_estimated_delivery_date (str).

=== 10 First Data ===
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
5  a4591c265e18cb1dcee52889e2d8acc3  503740e9ca751ccdda7ba28e9ab8f608
6  136cce7faa42fdb2cefd53fdc79a6098  ed0271e0b7da060a393796590e7b737a
7  6514b8ad8028c9f2cc2374ded245783f  9bdf08b4b3b52b5526ff42d37d47f222
8  76c6e866289321a7c93b82b54852dc33  f54a9f0e6b351c431402b8461ea51999
9  e69bfb5eb88e0ed6a785585b27e16dbf  31ad1d1b63eb9962463f764d4e6e0c9d

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29
5    delivered      2017-07-09 21:57:05  2017-07-09 22:10:13
6     invoiced      2017-04-11 12:22:08  2017-04-13 13:25:17
7    delivered      2017-05-16 13:10:30  2017-05-16 13:22:11
8    delivered      2017-01-23 18:29:09  2017-01-25 02:50:47
9    delivered      2017-07-29 11:55:02  2017-07-29 12:05:32

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02
5          2017-07-11 14:58:04           2017-07-26 10:57:55
6                          NaN                           NaN
7          2017-05-22 10:07:46           2017-05-26 12:55:51
8          2017-01-26 14:16:31           2017-02-02 14:08:10
9          2017-08-10 19:45:24           2017-08-16 17:14:30

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00
5           2017-08-01 00:00:00
6           2017-05-09 00:00:00
7           2017-06-07 00:00:00
8           2017-03-06 00:00:00
9           2017-08-23 00:00:00

=== NULL COUNT ===
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

=== DUPLICATE COUNT ===
0

==========================

Filename: olist_products_dataset.csv

=== SHAPE ===
(32951, 9)

=== DTYPES ===
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

=== COLUMNS ===
Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

Column and Its Type
product_id (str), product_category_name (str), product_name_lenght (float64), product_description_lenght (float64), product_photos_qty (float64), product_weight_g (float64), product_length_cm (float64), product_height_cm (float64), product_width_cm (float64).

=== 10 First Data ===
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas
5  41d3672d4792049fa1779bb35283ed13  instrumentos_musicais
6  732bd381ad09e530fe0a5f457d81becb             cool_stuff
7  2548af3e6e77a690cf3eb6368e9ab61e       moveis_decoracao
8  37cc742be07708b53a98702e77a21a02       eletrodomesticos
9  8c92109888e8cdf9d66dc7e463025574             brinquedos

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0
5                 60.0                       745.0                 1.0
6                 56.0                      1272.0                 4.0
7                 56.0                       184.0                 2.0
8                 57.0                       163.0                 1.0
9                 36.0                      1156.0                 1.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0
5             200.0               38.0                5.0              11.0
6           18350.0               70.0               24.0              44.0
7             900.0               40.0                8.0              40.0
8             400.0               27.0               13.0              17.0
9             600.0               17.0               10.0              12.0

=== NULL COUNT ===
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

=== DUPLICATE COUNT ===
0

==========================

Filename: olist_sellers_dataset.csv

=== SHAPE ===
(3095, 4)

=== DTYPES ===
seller_id                   str

In [4]:
df_customers = pd.read_csv('data/olist_customers_dataset.csv')
df_geo = pd.read_csv('data/olist_geolocation_dataset.csv')
df_sellers = pd.read_csv('data/olist_sellers_dataset.csv')
df_orders = pd.read_csv('data/olist_orders_dataset.csv')
df_products = pd.read_csv('data/olist_products_dataset.csv')
df_payments = pd.read_csv("data/olist_order_payments_dataset.csv")
df_items = pd.read_csv('data/olist_order_items_dataset.csv')
df_reviews = pd.read_csv('data/olist_order_reviews_dataset.csv')

In [5]:
df_products[['product_weight_g', 'product_height_cm', 'product_length_cm', 'product_width_cm']].describe()

,product_weight_g,product_height_cm,product_length_cm,product_width_cm
count,32949.000000,32949.000000,32949.000000,32949.000000
mean,2276.472488,16.937661,30.815078,23.196728
std,4282.038731,13.637554,16.914458,12.079047
min,0.000000,2.000000,7.000000,6.000000
25%,300.000000,8.000000,18.000000,15.000000
50%,700.000000,13.000000,25.000000,20.000000
75%,1900.000000,21.000000,38.000000,30.000000
max,40425.000000,105.000000,105.000000,118.000000

In [6]:
df_products[['product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty']].isna().sum()

product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
dtype: int64

In [7]:
not_defined = df_payments[df_payments['payment_type'] == 'not_defined']

merged = not_defined.merge(df_orders[['order_id', 'order_status']], on='order_id')

In [8]:
df_customers['customer_zip_code_prefix'].astype(str).str.len().value_counts()

df_geo['geolocation_zip_code_prefix'].astype(str).str.len().value_counts()

df_customers['customer_zip_code_prefix'].astype(str).head(10)

df_orders["order_status"].value_counts()

df_products["product_category_name"].value_counts().head(20)

df_geo['geolocation_city'].value_counts().head(20)

df_payments['payment_type'].value_counts()

df_items[['price', 'freight_value']].describe()

df_reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [9]:
not_defined

merged[['order_id', 'payment_type', 'order_status']]

                           order_id payment_type order_status
0  4637ca194b6387e2d538dc89b124b0ee  not_defined     canceled
1  00b1cb0320190ca0daa2c88b35206009  not_defined     canceled
2  c8c528189310eaa44a745b8d9d26908b  not_defined     canceled

In [10]:
df_products[df_products['product_category_name'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [11]:
null_category = df_products[df_products['product_category_name'].isna()]

null_category

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [12]:
(~df_payments['order_id'].isin(df_orders['order_id'])).sum()
(~df_items['order_id'].isin(df_orders['order_id'])).sum()
(~df_items['product_id'].isin(df_products['product_id'])).sum()
(~df_items['seller_id'].isin(df_sellers['seller_id'])).sum()
(~df_orders['customer_id'].isin(df_customers['customer_id'])).sum()

np.int64(0)

In [13]:
null_product_ids = null_category['product_id']
sold = null_product_ids.isin(df_items['product_id']).sum()

In [14]:
sold

np.int64(610)

In [15]:
null_dimensions = df_products[
    df_products['product_weight_g'].isna()
]

In [16]:

null_dimensions[['product_id', 'product_category_name', 'product_weight_g',
                       'product_length_cm', 'product_height_cm', 'product_width_cm']]

null_dimensions['product_id'].isin(df_items['product_id']).sum()

np.int64(2)

In [17]:
df_products['product_weight_g'].mean()

np.float64(2276.4724877841513)

In [18]:
df_products[df_products['product_category_name'] == 'bebes']['product_weight_g'].mean()

np.float64(3655.2015250544664)

In [19]:
df_products['product_category_name'].isna().sum()

np.int64(610)

In [20]:
df_geo['geolocation_zip_code_prefix'].value_counts()

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
         ...
97843       1
97960       1
98320       1
98825       1
99839       1
Name: count, Length: 19015, dtype: int64

In [21]:
df_geo['geolocation_city'].value_counts()

geolocation_city
sao paulo                     135800
rio de janeiro                 62151
belo horizonte                 27805
são paulo                      24918
curitiba                       16593
                               ...
são josé do herval                 1
almirante tamandaré do sul         1
são valentim                       1
três arroios                       1
ciríaco                            1
Name: count, Length: 8011, dtype: int64

In [22]:
df_geo['geolocation_city'].value_counts().head(40)

geolocation_city
sao paulo                135800
rio de janeiro            62151
belo horizonte            27805
são paulo                 24918
curitiba                  16593
porto alegre              13521
salvador                  11865
guarulhos                 11340
brasilia                  10470
sao bernardo do campo      8112
osasco                     7658
santo andre                6863
niteroi                    6534
recife                     6168
goiania                    5661
fortaleza                  5538
campinas                   5479
sorocaba                   5361
santos                     5000
barueri                    4971
juiz de fora               4679
contagem                   4395
campo grande               4332
ribeirao preto             4187
florianopolis              4148
nova iguacu                4022
mogi das cruzes            3913
belem                      3789
sao jose dos campos        3759
sao goncalo                3601
uberlandia                 3520
vitoria                    3478
duque de caxias            3444
bauru                      3270
sao jose do rio preto      3190
londrina                   3144
carapicuiba                3041
diadema                    2986
praia grande               2952
joinville                  2922
Name: count, dtype: int64

In [25]:
df_geo[df_geo['geolocation_city'].str.contains("paulo")]['geolocation_city'].value_counts()

geolocation_city
sao paulo                      135800
são paulo                       24918
paulo afonso                      434
engenheiro paulo de frontin        81
paulo de faria                     56
paulo frontin                      45
monsenhor paulo                    25
sao paulo das missoes              23
paulo lopes                        22
sao paulo do potengi               16
frei paulo                         11
paulo bento                         8
paulo jacinto                       7
paulo ramos                         7
sãopaulo                            2
morro de sao paulo                  2
são paulo do potengi                2
são paulo das missões               2
sa£o paulo                          1
morro de são paulo                  1
são paulo de olivença               1
sao paulo de olivenca               1
Name: count, dtype: int64

In [30]:
df_customers['customer_city'].nunique()

4119

In [36]:
df_customers[df_customers['customer_city'].str.contains("paulo")].value_counts()

customer_id                       customer_unique_id                customer_zip_code_prefix  customer_city  customer_state
4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e  1151                      sao paulo      SP                1
fd826e7cf63160e536e0908c76c3f441  addec96d2e059c80c30fe6871d30d177  4534                      sao paulo      SP                1
eabebad39a88bb6f5b52376faec28612  295c05e81917928d76245e842748184d  5704                      sao paulo      SP                1
9b8ce803689b3562defaad4613ef426f  7f3a72e8f988c6e735ba118d54f47458  5416                      sao paulo      SP                1
2938121a40a20953c43caa8c98787fcb  482441ea6a06b1f72fe9784756c0ea75  5713                      sao paulo      SP                1
                                                                                                                              ..
f6c6d3e1e20969a5eed982163f959719  fb354969e06f2093c0083cbfbb91864e  1521                      sao paulo      SP                1
da37711b17efd5f2539e8196ab215f04  5f2971f9805e3ccb030226e30c8e8390  4313                      sao paulo      SP                1
821a7275a08f32975caceff2e08ea262  046470763123d3d6364f89095b4e47ab  5734                      sao paulo      SP                1
c6ece8a5137f3c9c3a3a12302a19a2ac  aaf22868003377e859049dcf5f0b3fdf  1323                      sao paulo      SP                1
17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8  3937                      sao paulo      SP                1
Name: count, Length: 15606, dtype: int64

In [39]:
df_customers['customer_city'].value_counts().head(100)

customer_city
sao paulo               15540
rio de janeiro           6882
belo horizonte           2773
brasilia                 2131
curitiba                 1521
                        ...
ponta grossa              143
aracatuba                 141
governador valadares      141
manaus                    140
cariacica                 139
Name: count, Length: 100, dtype: int64

In [43]:
df_products[df_products['product_weight_g'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN